services:

  mariadb_db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: library_db
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8090:80"
